services:
  postgres:
    image: postgres:18.1-alpine
    container_name: fastapi-ecommerce-backend-database
    env_file: .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - fastapi-ecommerce-backend-database-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: fastapi-ecommerce-backend-pgadmin
    env_file: .env
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - postgres
    volumes:
      - fastapi-ecommerce-backend-pgadmin-data:/var/lib/pgadmin

  redis:
    image: redis:8.6-rc1-alpine3.23
    container_name: fastapi-ecommerce-backend-redis
    env_file: .env
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - fastapi-ecommerce-backend-redis-data:/data

  # prometheus:
  #   image: prom/prometheus:main-distroless
  #   container_name: fastapi-ecommerce-backend-prometheus
  #   volumes:
  #     - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  #   ports:
  #     - "9090:9090"

  # grafana:
  #   image: grafana/grafana:main
  #   container_name: fastapi-ecommerce-backend-grafana
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - prometheus

volumes:
  fastapi-ecommerce-backend-database-data:
  fastapi-ecommerce-backend-pgadmin-data:
  fastapi-ecommerce-backend-redis-data:
